title: Julia Melgare - Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Portfolio website of an aspiring Game Dev/Computer Graphics researcher. 
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Julia Melgare # add your name
author-img: julia_melgare.jpg # add your photo
about-author: Currently a Computer Science PhD student at PUCRS working in the area of facial and body motion behaviors in character animation. Has a bachelor's degree in Computer Science from PUCRS (2021) and worked as a scientific initiation student for two years at Virtual Humans Simulation Laboratory (VHLab) under the orientation of Prof. Dr. Soraia Raupp Musse. Has experience with computer animation focused on virtual characters, motion style in faces and bodies, facial recognition and data summarization. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: Julia-Melgare # add your Github handle
social-linkedin: julia-melgare-a6750a1a2 # add your Linkedin handle
social-email: julia.k.melgare@gmail.com # add your Email address
social-itchio: julia-melgare

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
