title: Julia Melgare - Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Portfolio website of an aspiring Game Dev/Computer Graphics researcher :) 
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Julia Melgare # add your name
author-img: julia_melgare.jpg # add your photo
about-author: I am a Computer Science bachelor with a passion for games, game development, and many other areas of computing such as Computer Graphics, Artificial Intelligence and Data Science. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Julia-Melgare # add your Github handle
social-linkedin: julia-melgare-a6750a1a2 # add your Linkedin handle
social-email: julia.melgare@acad.pucrs.br # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
